language: node_js
node_js:
  - "node"
  - "8"

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - echo $TRAVIS_NODE_VERSION
  - |
    if [ $TRAVIS_PULL_REQUEST == "false"]; then
      npm run snapshot;
    fi
  - npm test

after_script: greenkeeper-lockfile-upload
