language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"

before_install:
  - yarn global add greenkeeper-lockfile@2
  - export PATH=$PATH:`yarn global bin`

before_script:
  - greenkeeper-lockfile-update
  - greenkeeper-lockfile-upload

script:
  - |
    if [[ $TRAVIS_PULL_REQUEST != "false" ]] && [[ $TRAVIS_NODE_VERSION == "node" ]]; then
      echo "Sending PR snapshots to Percy";
      npm run snapshot;
    elif [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_NODE_VERSION == "node" ]]; then
      echo "Sending master build snapshots to Percy";
      npm run snapshot;
    else
      echo "Skipping snapshot. Node version and pull request:";
      echo $TRAVIS_NODE_VERSION;
      echo $TRAVIS_PULL_REQUEST;
    fi
  - npm test

