language: node_js
node_js:
  - "node"
  - "8"

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - '[[ $TRAVIS_PULL_REQUEST != "false" ]] && npm run snapshot'
  - npm test

after_script: greenkeeper-lockfile-upload
