language: node_js
node_js:
  - "node"
  - "8"

# TODO: Switch this back to yarn when greenkeeperio/greenkeeper-lockfile#98 is fixed.
# https://github.com/greenkeeperio/greenkeeper-lockfile/issues/98
# before_install: yarn global add greenkeeper-lockfile@1
before_install: npm install --global greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - |
    if [[ $TRAVIS_PULL_REQUEST != "false" ]] && [[ $TRAVIS_NODE_VERSION == "node" ]]; then
      echo "Sending PR snapshots to Percy";
      npm run snapshot;
    elif [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
      echo "Sending master build snapshots to Percy";
      npm run snapshot;
    else
      echo "Skipping snapshot. Node version and pull request:";
      echo $TRAVIS_NODE_VERSION;
      echo $TRAVIS_PULL_REQUEST;
    fi
  - npm test

after_script: greenkeeper-lockfile-upload
