addons:
  firefox: "63.0"

language: node_js
node_js:
  - "node"
  - "10"
  - "8"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - |
    if [[ $TRAVIS_PULL_REQUEST != "false" ]] && [[ $TRAVIS_NODE_VERSION == "node" ]]; then
      firefox -v
      echo "Sending PR snapshots to Percy";
      npm run snapshot;
    elif [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_NODE_VERSION == "node" ]]; then
      echo "Sending master build snapshots to Percy";
      npm run snapshot;
    else
      echo "Skipping snapshot. Node version and pull request:";
      echo $TRAVIS_NODE_VERSION;
      echo $TRAVIS_PULL_REQUEST;
    fi
  - npm test
