language: node_js
node_js:
  - "node"
  - "8"

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - echo $TRAVIS_NODE_VERSION
  - |
    # Only run percy on push builds
    # Also, only run percy once per push
    if
      [ $TRAVIS_PULL_REQUEST == "false" ]
      && [ $TRAVIS_NODE_VERISON == "node" ]
    ; then
      npm run snapshot;
    fi
  - npm test

after_script: greenkeeper-lockfile-upload
