addons:
  firefox: "63.0"

language: node_js
node_js:
  - "node"
  - "10"
  - "8"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - |
    if [[ $TRAVIS_EVENT_TYPE != 'pull_request' ||  $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]];
    then
      npm run chromatic
    fi
  - npm test
