module.exports = 
{ name: 'Dagbladet',
  global: '\n\t@import url(\'https://fonts.googleapis.com/css?family=Roboto:300,700,800\');\n\n\t\n\thtml, body, div, span, applet, object, iframe,\n\th1, h2, h3, h4, h5, h6, p, blockquote, pre,\n\ta, abbr, acronym, address, big, cite, code,\n\tdel, dfn, em, font, ins, kbd, q, s, samp,\n\tsmall, strike, strong, sub, sup, tt, var,\n\tdl, dt, dd, ol, ul, li,\n\tfieldset, form, label, legend,\n\ttable, caption, tbody, tfoot, thead, tr, th, td {\n\t\tmargin: 0;\n\t\tpadding: 0;\n\t\tborder: 0;\n\t\tfont-size: 100%;\n\t\tfont: inherit;\n\t\tvertical-align: baseline;\n\t\tword-wrap: break-word;\n\t}\n\n\thtml {\n\t\tfont-size: 62.5%; /* Corrects text resizing oddly in IE6/7 when body font-size is set using em units http://clagnut.com/blog/348/#c790 */\n\t\t-webkit-text-size-adjust: 100%; /* Prevents iOS text size adjust after orientation change, without disabling user zoom */\n\t\t-ms-text-size-adjust:     100%; /* www.456bereastreet.com/archive/201012/controlling_text_size_in_safari_for_ios_without_disabling_user_zoom/ */\n\t}\n\n\t*,\n\t*::before,\n\t*::after { /* apply a natural box layout model to all elements; see http://www.paulirish.com/2012/box-sizing-border-box-ftw/ */\n\t\tbox-sizing: border-box;\n\t}\n\n\tbody {\n\t\tfont-size: 1.6rem; /* Reset the body text to 16px */\n\t\tline-height: 1;\n\t\tbackground: transparent;\n\t}\n\n\t/* HTML5 display-role reset for older browsers */\n\tarticle, aside, details, figcaption, figure,\n\tfooter, header, hgroup, main, menu, nav, section {\n\t\tdisplay: block;\n\t}\n\n\t/* HTML5 hidden-attribute fix for newer browsers */\n\t*[hidden] {\n\t    display: none;\n\t}\n\n\tol, ul {\n\t\tlist-style: none;\n\t}\n\n\t/* tables still need \'cellspacing="0"\' in the markup */\n\ttable {\n\t\tborder-collapse: separate;\n\t\tborder-spacing: 0;\n\t}\n\n\tcaption, th, td {\n\t\tfont-weight: normal;\n\t\ttext-align: left;\n\t}\n\n\tblockquote, q {\n\t\tquotes: none;\n\t}\n\n\tblockquote:before, blockquote:after,\n\tq:before, q:after {\n\t\tcontent: \'\';\n\t\tcontent: none;\n\t}\n\n\ta:focus {\n\t\toutline: thin dotted;\n\t}\n\n\ta:hover,\n\ta:active {\n\t\toutline: 0;\n\t}\n\n\ta {\n\t\timg {\n\t\t\tborder: 0;\n\t\t}\n\t}\n\n\tp {\n\t\tmargin-bottom: 1em;\n\t}\n\n',
  colors: 
   { grayTint: '#C0C0C0',
     grayTintLight: '#ECECEC',
     grayTintLightDark: '#C0C0C0',
     grayTintLighter: '#f3f3f3',
     grayTintDark: '#767676',
     white: '#fff',
     darkness: '#222222',
     darknessLight: '#453d3f',
     darknessLighter: '#342c2e',
     darknessDark: '#111111',
     buttonBackground: '#ececec',
     buttonColor: '#3768c9',
     primary: '#d60000',
     primaryDark: '#bd0000',
     primaryLight: '#ff2323',
     primaryLighter: '#ff7070',
     secondary: '#ECECEC',
     secondaryDark: '#dfdfdf',
     secondaryLight: '#fff',
     secondaryLighter: '#fff',
     pink: '#F35D67',
     pinkDark: '#f14551',
     pinkLight: '#f8a4aa',
     pinkLighter: '#feebed',
     purple: '#5C3393',
     purpleDark: '#502c80',
     purpleLight: '#8150c2',
     purpleLighter: '#aa89d6',
     blue: '#23ACCC',
     blueDark: '#1f9ab6',
     blueLight: '#59c8e3',
     blueLighter: '#9adeee',
     teal: '#569091',
     tealDark: '#4d8081',
     tealLight: '#80b3b4',
     tealLighter: '#b0d0d0',
     green: '#8ABA56',
     greenDark: '#7daf47',
     greenLight: '#b0d08c',
     greenLighter: '#d5e6c3',
     yellow: '#F1CA3F',
     yellowDark: '#efc327',
     yellowLight: '#f6de86',
     yellowLighter: '#fbf1ce',
     orange: '#E87E0A',
     orangeDark: '#d07109',
     orangeLight: '#f7a347',
     orangeLighter: '#fac891',
     navy: '#1C1837',
     navyDark: '#131025',
     navyLight: '#372f6c',
     navyLighter: '#5246a2',
     burgundy: '#862547',
     burgundyDark: '#721f3c',
     burgundyLight: '#c23667',
     burgundyLighter: '#d76d92',
     brown: '#9a663f',
     brownDark: '#885a38',
     brownLight: '#c08c65',
     brownLighter: '#d6b59c',
     skinColors: 
      { type: 'darkness',
        nativeAd: 'green',
        splashBackground: 'primary',
        splashText: 'white' } },
  variables: 
   { mainFont: '"Roboto","Helvetica",Helvetica,Arial,sans-serif',
     headingsFont: '"Roboto","Helvetica",Helvetica,Arial,sans-serif',
     uiWeight: 300,
     uiRegularSize: '1.6rem',
     uiRegularLineHeight: '2.4rem' } }
