const dorisIcons = {
	'bell': () => import('./Bell'),
	'bookmark': () => import('./Bookmark'),
	'car': () => import('./Car'),
	'coins': () => import('./Coins'),
	'concentric-circles': () => import('./ConcentricCircles'),
	'dice': () => import('./Dice'),
	'document-alt': () => import('./DocumentAlt'),
	'document': () => import('./Document'),
	'documents': () => import('./Documents'),
	'food': () => import('./Food.js'),
	'gear': () => import('./Gear'),
	'globe': () => import('./Globe'),
	'grid': () => import('./Grid'),
	'heart-line': () => import('./HeartLine'),
	'heart': () => import('./Heart'),
	'home-alt': () => import('./HomeAlt'),
	'home': () => import('./Home'),
	'horizontal-ellipse': () => import('./HorizontalEllipse'),
	'horoscope': () => import('./Horoscope'),
	'lightning': () => import('./Lightning'),
	'magnifier': () => import('./Magnifier.js'),
	'medal': () => import('./Medal'),
	'olympic-flame': () => import('./OlympicFlame'),
	'olympic-rings': () => import('./OlympicRings'),
	'pin': () => import('./Pin'),
	'running': () => import('./Running'),
	'scale': () => import('./Scale'),
	'share': () => import('./Share'),
	'silhouette': () => import('./Silhouette'),
	'sliders': () => import('./Sliders'),
	'speech-bubble-question': () => import('./SpeechBubbleQuestion'),
	'speech-bubble': () => import('./SpeechBubble'),
	'speech-bubbles': () => import('./SpeechBubbles'),
	'star': () => import('./Star'),
	'suitcase': () => import('./Suitcase'),
	'television': () => import('./Television'),
	'trash': () => import('./Trash.js'),
	'vertical-ellipse': () => import('./VerticalEllipse'),

	// Aliases
	'copy': () => import('./Documents'),
	'favorite': () => import('./Heart'),
	'favourite': () => import('./Heart'),
	'search': () => import('./Magnifier.js'),
	'bin': () => import('./Trash.js'),
	'breaking': () => import('./ConcentricCircles'),
	'similar-stories': () => import('./Documents'),
	'cardio': () => import('./HeartLine'),
	'comment': () => import('./SpeechBubble'),
	'newspaper': () => import('./DocumentAlt'),
	'question': () => import('./SpeechBubbleQuestion'),
	'athletics': () => import('./Running'),
	'exit': () => import('./Running'),
	'tv': () => import('./Television'),
	'money': () => import('./Coins'),
	'user': () => import('./Silhouette'),
	'comments': () => import('./SpeechBubbles'),

	// tabNav
	'categories': () => import('./Grid'),
	'settings': () => import('./Gear'),

	// Kategorier
	'recommendation': () => import('./Star'),
	'review': () => import('./Dice'),
	'health': () => import('./HeartLine'),
	'opinion': () => import('./SpeechBubble'),
	'motor': () => import('./Car'),
	'news': () => import('./DocumentAlt'),
	'politics': () => import('./Scale'),
	'quiz': () => import('./SpeechBubbleQuestion'),
	'travel': () => import('./Suitcase'),
	'sports': () => import('./Running'),
	'entertainment': () => import('./Television'),
	'world': () => import('./Globe'),
	'finance': () => import('./Coins'),

	// Innstillingssiden
	'settings-alt': () => import('./Sliders'),
	'profile': () => import('./Silhouette'),
	'privacy': () => import('./Document'),
	'position': () => import('./Pin'),
	'feedback': () => import('./SpeechBubbles'),
	'notification': () => import('./Bell'),
	'new-tab': () => import('./NewTab'),
};

export default dorisIcons;
