export default {
	mainFont: '"Cabin", "Roboto","Helvetica",Helvetica,Arial,sans-serif',
	headingsFont: '"Cabin",sans-serif',
	horizontalBase: '1rem',
	uiRegularSize: '1.6rem',

	// headingSmallSize: '1.6rem',
	// headingSmallLineHeight: '2.3rem',
	headingSmallSize: '2.0rem',
	headingSmallLineHeight: '2.7rem',
	headingMediumSize: '2.0rem',
	headingMediumLineHeight: '2.7rem',
	headingRegularSize: '2.0rem',
	headingRegularLineHeight: '2.7rem',
	headingLargeSize: '2.2rem',
	headingLargeLineHeight: '2.7rem',
	headingXlargeSize: '2.8rem',
	headingXlargeLineHeight: '3.3rem',
	headingHugeSize: '3.8rem',
	headingHugeLineHeight: '6.4rem',

	headingSmallSizeMobile: '4.6rem',
	headingSmallLineHeightMobile: '4.6rem',
	headingMediumSizeMobile: '4.8rem',
	headingMediumLineHeightMobile: '4.8rem',
	headingRegularSizeMobile: '5rem',
	headingRegularLineHeightMobile: '6.1rem',
	headingLargeSizeMobile: '5.2rem',
	headingLargeLineHeightMobile: '6.1rem',
	headingXlargeSizeMobile: '5.4rem',
	headingXlargeLineHeightMobile: '6.1rem',
	headingHugeSizeMobile: '5.6rem',
	headingHugeLineHeightMobile: '6.3rem',


};
