import React from 'react';

// Components

// Atoms
import { Wrapper } from '../atoms/MainRecipe/Wrapper';
import { ComplexitySection } from '../atoms/MainRecipe/ComplexitySection';
import { ComplexitySectionHeader } from '../atoms/MainRecipe/ComplexitySectionHeader';
import { Description } from '../atoms/MainRecipe/Description';
import { Col } from '../atoms/Col';
import { Row } from '../atoms/Row';

// Molecules
import { MainRecipeImage } from '../molecules/MainRecipe/MainRecipeImage';
import { IconsBar } from '../molecules/MainRecipe/IconsBar';
import { DetailsSection } from '../molecules/MainRecipe/DetailsSection';
// Organisms
import { Steps } from './Steps';

const fakeProp = {
			"id": 276,
			"views": 16708,
			"title": "Helstekt kalkun",
			"slug": "helstekt-kalkun",
			"description_short": "Helstekt kalkun er en selvfølge på middagsbordet ved Thanksgiving, jul og nyttår! For en smakfull og saftig kalkun anbefaler vi denne oppskriften.",
			"description": "<p>Helstekt kalkun&nbsp;er en selvf&oslash;lge p&aring; middagsbordet ved Thanksgiving, jul og nytt&aring;r!&nbsp;For en smakfull og saftig kalkun anbefaler vi denne oppskriften.</p>",
			"time_total": 165,
			"time_cooking": 15,
			"difficulty": 1,
			"servings": 10,
			"heat_scale": 0,
			"is_sponsored": 0,
			"sponsor_name": null,
			"published_from": "2015-11-24 00:00:00",
			"published_to": null,
			"created_by": {
				"id": 5,
				"first_name": "Merethe",
				"last_name": "",
				"full_name": "Merethe "
			},
			"updated_by": {
				"id": 3,
				"first_name": "Elisabeth",
				"last_name": "",
				"full_name": "Elisabeth "
			},
			"created_at": "2015-11-24 16:45:09",
			"updated_at": "2017-05-14 19:32:02",
			"draft": 0,
			"numVotes": 0,
			"rating": 0,
			"maxRating": null,
			"minRating": null,
			"url": "http://www.dagbladet.medialaben.no/mat/oppskrift/helstekt-kalkun",
			"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/oppskrift/helstekt-kalkun",
			"time_prep": 150,
			"images": [
				{
					"id": 735,
					"is_profile": 0,
					"type": 3,
					"file_name": "f84b0f9c",
					"size": 1106289,
					"width": 3000,
					"height": 1996,
					"title": "Helstekt kalkun",
					"description": "<p><strong>SMAKFULL OG SAFTIG:</strong> Kalkun er et festm&aring;ltid du kan spise med god samvittighet.</p>",
					"byline": "matprat.no / Studio Dreyer-Hensley",
					"byline_url": "http://www.matprat.no/",
					"created_by": 5,
					"updated_by": 5,
					"created_at": "2015-11-24 16:47:32",
					"updated_at": "2015-11-24 16:47:32",
					"type_original": 0,
					"url_s_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/1/f84b0f9c-helstekt-kalkun.jpg",
					"url_m_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/1/f84b0f9c-helstekt-kalkun.jpg",
					"url_l_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/1/f84b0f9c-helstekt-kalkun.jpg",
					"url_xl_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/1/f84b0f9c-helstekt-kalkun.jpg",
					"url_s_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/2/f84b0f9c-helstekt-kalkun.jpg",
					"url_m_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/2/f84b0f9c-helstekt-kalkun.jpg",
					"url_l_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/2/f84b0f9c-helstekt-kalkun.jpg",
					"url_xl_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/2/f84b0f9c-helstekt-kalkun.jpg",
					"url_s_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/3/f84b0f9c-helstekt-kalkun.jpg",
					"url_m_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/3/f84b0f9c-helstekt-kalkun.jpg",
					"url_l_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/3/f84b0f9c-helstekt-kalkun.jpg",
					"url_xl_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/3/f84b0f9c-helstekt-kalkun.jpg",
					"seo_file_name": "f84b0f9c-helstekt-kalkun.jpg"
				}
			],
			"categories": [
				{
					"id": 7,
					"type": 2,
					"title": "Middag",
					"slug": "middag",
					"slug_labrador": "middag",
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrifter/kategori/middag"
				}
			],
			"steps": [
				{
					"id": 1312,
					"video_id": null,
					"description": "<p>Ta ut innmaten. Dette er god basis for saus, s&aring; ta vare p&aring; det.&nbsp;</p>",
					"sort_order": 0,
					"category": null,
					"created_by": 5,
					"updated_by": 5,
					"images": [

					]
				},
				{
					"id": 1313,
					"video_id": null,
					"description": "<p>Bind l&aring;rene sammen ved benknokene. Sitter vingespissene p&aring;, f&oslash;r dem bak ryggen inn mot halsen. Slik at vingene hviler under og st&oslash;tter kalkunen.</p>",
					"sort_order": 1,
					"category": null,
					"created_by": 5,
					"updated_by": 5,
					"images": [

					]
				},
				{
					"id": 1314,
					"video_id": null,
					"description": "<p>Legg kalkunen over i en langpanne eller ildfast form. Smelt sm&oslash;r, tilsett salt og pepper og pensle kalkunen med blandingen.</p>",
					"sort_order": 2,
					"category": null,
					"created_by": 5,
					"updated_by": 5,
					"images": [

					]
				},
				{
					"id": 1315,
					"video_id": null,
					"description": "<p>Hell p&aring; vann og sett kalkunen inn i en forvarmet stekeovn p&aring; 180 &deg;C.&nbsp;Beregn ca. en halv time pr. kilo. Pensle kalkunen med smeltet sm&oslash;r eller kraften som har dannet seg i formen flere ganger under steketiden. Det vil gi ekstra smak og flott gyllen farge p&aring; skinnet.</p>",
					"sort_order": 3,
					"category": null,
					"created_by": 5,
					"updated_by": 5,
					"images": [

					]
				},
				{
					"id": 1316,
					"video_id": null,
					"description": "<p>Stikk en spiss kniv inn ved l&aring;rfestet. Kommer det klar kraft ut er kalkunen ferdig.&nbsp;La kalkunen hvile i minst 20 minutter f&oslash;r du skj&aelig;rer i den. Flytt etter noen minutter kalkunen over p&aring; en fj&oslash;l eller et fat, og pakk den inn i&nbsp;aluminiumfolie&nbsp;dersom den skal serveres varm.</p>",
					"sort_order": 4,
					"category": null,
					"created_by": 5,
					"updated_by": 5,
					"images": [

					]
				}
			],
			"tags": [
				{
					"id": 13,
					"title": "Fugl",
					"slug": "fugl",
					"slug_labrador": "fugl",
					"created_by": 1,
					"updated_by": 1,
					"created_at": "2015-07-13 08:27:46",
					"updated_at": "2015-07-13 08:27:46",
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrifter/tag/fugl"
				},
				{
					"id": 52,
					"title": "Tradisjon",
					"slug": "tradisjon",
					"slug_labrador": "",
					"created_by": 5,
					"updated_by": 5,
					"created_at": "2015-10-28 18:09:52",
					"updated_at": "2015-10-28 18:09:52",
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrifter/tag/tradisjon"
				},
				{
					"id": 90,
					"title": "Grunnoppskrift",
					"slug": "grunnoppskrift",
					"slug_labrador": "",
					"created_by": 5,
					"updated_by": 5,
					"created_at": "2015-10-28 18:16:35",
					"updated_at": "2015-10-28 18:16:35",
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrifter/tag/grunnoppskrift"
				},
				{
					"id": 50,
					"title": "Fest",
					"slug": "fest",
					"slug_labrador": "",
					"created_by": 5,
					"updated_by": 5,
					"created_at": "2015-10-28 18:09:36",
					"updated_at": "2015-10-28 18:09:36",
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrifter/tag/fest"
				},
				{
					"id": 8,
					"title": "Festmat",
					"slug": "festmat",
					"slug_labrador": "festmat",
					"created_by": 1,
					"updated_by": 1,
					"created_at": "2015-07-13 08:27:46",
					"updated_at": "2015-07-13 08:27:46",
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrifter/tag/festmat"
				}
			],
			"editorials": [
				{
					"id": 1,
					"title": "Dagbladet",
					"slug": "dagbladet",
					"created_by": 1,
					"updated_by": 1,
					"created_at": "2015-11-02 14:30:36",
					"updated_at": "2015-11-02 14:30:36"
				}
			],
			"authors": [
				{
					"id": 7,
					"views": 763,
					"name": "Matprat",
					"slug": "matprat",
					"profile_image_id": 368,
					"email": "mat@dagbladet.no",
					"external_url": null,
					"description_short": "Opplysningskontoret for egg og kjøtt (OEK) er Norges fremste kompetansesenter for matopplysning. ",
					"description": "<p><span style=\"color: #262626; font-family: Neutra2Text, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 18.0625px; line-height: 25.2875px;\">Opplysningskontoret for egg og kj&oslash;tt (OEK) er Norges fremste kompetansesenter for matopplysning.</span></p>",
					"facebook": "https://www.facebook.com/MatPrat/",
					"instagram": "https://instagram.com/matprat.no/",
					"pinterest": null,
					"snapchat": null,
					"twitter": null,
					"web_page": "http://www.matprat.no/",
					"is_chef": 0,
					"is_company": 1,
					"published_from": "2015-07-13 08:27:45",
					"published_to": null,
					"created_by": 1,
					"updated_by": 5,
					"created_at": "2015-07-13 08:27:45",
					"updated_at": "2017-05-13 15:39:02",
					"url": "http://www.dagbladet.medialaben.no/mat/kokk/matprat",
					"pivot": {
						"authorable_id": 276,
						"author_id": 7
					},
					"profile_image": {
						"id": 368,
						"is_profile": 1,
						"type": 3,
						"file_name": "3e67492f",
						"size": 9526,
						"width": 400,
						"height": 412,
						"title": "Matprat logo",
						"description": null,
						"byline": "Matprat.no",
						"byline_url": "http://www.matprat.no",
						"created_by": 3,
						"updated_by": 3,
						"created_at": "2015-07-27 12:58:49",
						"updated_at": "2015-07-27 12:58:49",
						"type_original": 0,
						"url_s_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/1/3e67492f-matprat-logo.jpg",
						"url_m_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/1/3e67492f-matprat-logo.jpg",
						"url_l_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/1/3e67492f-matprat-logo.jpg",
						"url_xl_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/1/3e67492f-matprat-logo.jpg",
						"url_s_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/2/3e67492f-matprat-logo.jpg",
						"url_m_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/2/3e67492f-matprat-logo.jpg",
						"url_l_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/2/3e67492f-matprat-logo.jpg",
						"url_xl_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/2/3e67492f-matprat-logo.jpg",
						"url_s_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/3/3e67492f-matprat-logo.jpg",
						"url_m_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/3/3e67492f-matprat-logo.jpg",
						"url_l_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/3/3e67492f-matprat-logo.jpg",
						"url_xl_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/3/3e67492f-matprat-logo.jpg",
						"seo_file_name": "3e67492f-matprat-logo.jpg"
					}
				}
			],
			"ingredients": [
				{
					"id": 435,
					"views": 797,
					"title": "Kalkun",
					"slug": "kalkun",
					"description_short": null,
					"description": "<p>Kalkunkj&oslash;tt h&oslash;rer hjemme i kategorien hvitt kj&oslash;tt sammen med kylling, og er b&aring;de sunt og magert. Kj&oslash;ttet er mildt og m&oslash;rt, med litt mer tyggemotstand enn kylling. Likt som hos kylling er det litt forskjell i kj&oslash;ttet p&aring; bryst og l&aring;r. Brystkj&oslash;ttet er helt lyst og mildt i smak, mens l&aring;rkj&oslash;ttet har mer markant smak og er m&oslash;rkere i fargen. M&oslash;rheten gj&oslash;r kj&oslash;ttet anvendelig, b&aring;de som festmat og til travle hverdager.&nbsp;P&aring; grunn av den milde smaken, passer kalkunkj&oslash;ttet til de fleste krydder og tilbeh&oslash;r.</p>",
					"preference_type": 1,
					"calories": 133.2,
					"fat": 5.2,
					"protein": 21.6,
					"carbohydrates": 0,
					"storage": "Kjøleskap, 0-4 grader",
					"shelf_life_from": 2,
					"shelf_life_to": 3,
					"shelf_life_type": 1,
					"origin": "Sør- og Mellom-Amerika",
					"is_sponsored": 0,
					"sponsor_name": null,
					"default_amount_type_id": null,
					"published_from": "2015-11-23 00:00:00",
					"published_to": null,
					"created_by": 5,
					"updated_by": 5,
					"created_at": "2015-11-24 16:22:29",
					"updated_at": "2017-05-05 17:01:02",
					"url": "http://www.dagbladet.medialaben.no/mat/ingrediens/kalkun",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/ingrediens/kalkun",
					"pivot": {
						"recipe_id": 276,
						"ingredient_id": 435,
						"id": 2695,
						"amount": 1,
						"amount_type_id": 12,
						"variant": "ca. fem kilo",
						"sort_order": 0,
						"category": null,
						"is_searchable": 1
					},
					"allergies": [

					],
					"categories": [
						{
							"id": 19,
							"type": 3,
							"title": "Kjøttdisken",
							"slug": "kjottdisken",
							"slug_labrador": "kjøttdisken",
							"url": "http://www.dagbladet.medialaben.no/mat/oppskrifter/kategori/kjottdisken"
						}
					]
				},
				{
					"id": 78,
					"views": 6162,
					"title": "Smør",
					"slug": "smor",
					"description_short": null,
					"description": "<p>Sm&oslash;r er et naturprodukt basert p&aring; fl&oslash;te. Sm&oslash;rtilberedning er utviklet som en konserveringsmetode og er kjent i alle kulturer som har holdt husdyr.&nbsp;I melk og fl&oslash;te finnes fett i sm&aring; kuler. Det er disse sm&aring; fettkulene som utvinnes i sm&oslash;rproduksjon. Mesteparten av sm&oslash;ret blir produsert av &ldquo;s&oslash;t&rdquo; fl&oslash;te.&nbsp;Sm&oslash;r passer meget godt til alle typer matlaging; steking, baking, sauser, supper og br&oslash;dmat.</p>",
					"preference_type": 2,
					"calories": 746,
					"fat": 82,
					"protein": 1,
					"carbohydrates": 1,
					"storage": "Kjøleskap, 0-4 grader",
					"shelf_life_from": null,
					"shelf_life_to": null,
					"shelf_life_type": null,
					"origin": null,
					"is_sponsored": 0,
					"sponsor_name": null,
					"default_amount_type_id": null,
					"published_from": "2015-06-15 08:26:09",
					"published_to": null,
					"created_by": 5,
					"updated_by": 5,
					"created_at": "2015-06-10 15:19:35",
					"updated_at": "2017-05-15 00:41:02",
					"url": "http://www.dagbladet.medialaben.no/mat/ingrediens/smor",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/ingrediens/smor",
					"pivot": {
						"recipe_id": 276,
						"ingredient_id": 78,
						"id": 2696,
						"amount": 100,
						"amount_type_id": 2,
						"variant": "til pensling",
						"sort_order": 1,
						"category": null,
						"is_searchable": 1
					},
					"allergies": [

					],
					"categories": [
						{
							"id": 20,
							"type": 3,
							"title": "Meieri",
							"slug": "meieri",
							"slug_labrador": "meieri",
							"url": "http://www.dagbladet.medialaben.no/mat/oppskrifter/kategori/meieri"
						}
					]
				},
				{
					"id": 51,
					"views": 8568,
					"title": "Salt",
					"slug": "salt",
					"description_short": null,
					"description": "<p>Koksalt eller natriumklorid er et salt, og er en kombinasjon av grunnstoffene natrium og klor, og er kjent som vanlig bordsalt.&nbsp;Salt brukes som smakstilsetning i mat og som det mest utbredte konserveringsmiddel for kj&oslash;tt, fisk og meieriprodukter.&nbsp;</p>",
					"preference_type": 3,
					"calories": 0,
					"fat": 0,
					"protein": 0,
					"carbohydrates": 0,
					"storage": "Romtemperatur, 18-25 grader",
					"shelf_life_from": 5,
					"shelf_life_to": 6,
					"shelf_life_type": 4,
					"origin": null,
					"is_sponsored": 0,
					"sponsor_name": null,
					"default_amount_type_id": null,
					"published_from": "2015-06-15 08:26:09",
					"published_to": null,
					"created_by": 5,
					"updated_by": 5,
					"created_at": "2015-06-09 12:06:59",
					"updated_at": "2017-05-15 01:05:02",
					"url": "http://www.dagbladet.medialaben.no/mat/ingrediens/salt",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/ingrediens/salt",
					"pivot": {
						"recipe_id": 276,
						"ingredient_id": 51,
						"id": 2697,
						"amount": 1.5,
						"amount_type_id": 10,
						"variant": null,
						"sort_order": 2,
						"category": null,
						"is_searchable": 1
					},
					"allergies": [

					],
					"categories": [
						{
							"id": 21,
							"type": 3,
							"title": "Tørrvarer",
							"slug": "torrvarer",
							"slug_labrador": "tørrvarer",
							"url": "http://www.dagbladet.medialaben.no/mat/oppskrifter/kategori/torrvarer"
						}
					]
				},
				{
					"id": 61,
					"views": 5832,
					"title": "Svart pepper",
					"slug": "svart-pepper",
					"description_short": null,
					"description": "<p>Svart pepper er et krydder fremstilt av fermenterte, t&oslash;rkede og umodne r&oslash;de b&aelig;r, kalt pepperkorn, fra planten Piper nigrum.&nbsp;Svart pepper er ett av de vanligste krydder i det europeiske og de europeiskinspirerte kj&oslash;kken. Smaken er sterk og brennende.</p>",
					"preference_type": 3,
					"calories": 276.7,
					"fat": 3.3,
					"protein": 10.4,
					"carbohydrates": 38.7,
					"storage": "Romtemperatur, 18-25 grader",
					"shelf_life_from": null,
					"shelf_life_to": null,
					"shelf_life_type": null,
					"origin": null,
					"is_sponsored": 0,
					"sponsor_name": null,
					"default_amount_type_id": null,
					"published_from": "2015-06-15 08:26:09",
					"published_to": null,
					"created_by": 5,
					"updated_by": 5,
					"created_at": "2015-06-09 15:45:39",
					"updated_at": "2017-05-14 21:51:02",
					"url": "http://www.dagbladet.medialaben.no/mat/ingrediens/svart-pepper",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/ingrediens/svart-pepper",
					"pivot": {
						"recipe_id": 276,
						"ingredient_id": 61,
						"id": 2698,
						"amount": 1.5,
						"amount_type_id": 10,
						"variant": null,
						"sort_order": 3,
						"category": null,
						"is_searchable": 1
					},
					"allergies": [

					],
					"categories": [
						{
							"id": 21,
							"type": 3,
							"title": "Tørrvarer",
							"slug": "torrvarer",
							"slug_labrador": "tørrvarer",
							"url": "http://www.dagbladet.medialaben.no/mat/oppskrifter/kategori/torrvarer"
						}
					]
				},
				{
					"id": 52,
					"views": 3758,
					"title": "Vann",
					"slug": "vann",
					"description_short": null,
					"description": "<p>Vann&nbsp;er en fargel&oslash;s v&aelig;ske med&nbsp;kjemisk forbindelse mellom hydrogen og oksygen, H₂O. Vann viser som regel fargen p&aring; stoffene bak eller rundt, eller reflekterer lyset som treffer vannoverflaten.&nbsp;De kjemiske egenskapene til vann er godt egnet til mange funksjoner i levende organismer. Vann har en rekke livsviktige funksjoner i menneskekroppen.&nbsp;Rent vann g&aring;r aldri ut p&aring; dato, s&aring;fremt det oppbevares i tett emballasje,&nbsp;men kan f&oslash;les litt flatt</p>",
					"preference_type": 3,
					"calories": 0,
					"fat": 0,
					"protein": 0,
					"carbohydrates": 0,
					"storage": "Romtemperatur, 18-25 grader",
					"shelf_life_from": 12,
					"shelf_life_to": 14,
					"shelf_life_type": 3,
					"origin": null,
					"is_sponsored": 0,
					"sponsor_name": null,
					"default_amount_type_id": null,
					"published_from": "2015-06-15 08:26:09",
					"published_to": null,
					"created_by": 5,
					"updated_by": 5,
					"created_at": "2015-06-09 12:07:10",
					"updated_at": "2017-05-14 11:32:02",
					"url": "http://www.dagbladet.medialaben.no/mat/ingrediens/vann",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/ingrediens/vann",
					"pivot": {
						"recipe_id": 276,
						"ingredient_id": 52,
						"id": 2699,
						"amount": 3,
						"amount_type_id": 7,
						"variant": null,
						"sort_order": 4,
						"category": null,
						"is_searchable": 1
					},
					"allergies": [

					],
					"categories": [
						{
							"id": 13,
							"type": 3,
							"title": "Drikkevarer",
							"slug": "drikkevarer",
							"slug_labrador": "drikkevarer",
							"url": "http://www.dagbladet.medialaben.no/mat/oppskrifter/kategori/drikkevarer"
						}
					]
				}
			],
			"related_articles": [

			],
			"related_ingredients": [
				{
					"id": 435,
					"views": 797,
					"title": "Kalkun",
					"slug": "kalkun",
					"description_short": null,
					"description": "<p>Kalkunkj&oslash;tt h&oslash;rer hjemme i kategorien hvitt kj&oslash;tt sammen med kylling, og er b&aring;de sunt og magert. Kj&oslash;ttet er mildt og m&oslash;rt, med litt mer tyggemotstand enn kylling. Likt som hos kylling er det litt forskjell i kj&oslash;ttet p&aring; bryst og l&aring;r. Brystkj&oslash;ttet er helt lyst og mildt i smak, mens l&aring;rkj&oslash;ttet har mer markant smak og er m&oslash;rkere i fargen. M&oslash;rheten gj&oslash;r kj&oslash;ttet anvendelig, b&aring;de som festmat og til travle hverdager.&nbsp;P&aring; grunn av den milde smaken, passer kalkunkj&oslash;ttet til de fleste krydder og tilbeh&oslash;r.</p>",
					"preference_type": 1,
					"calories": 133.2,
					"fat": 5.2,
					"protein": 21.6,
					"carbohydrates": 0,
					"storage": "Kjøleskap, 0-4 grader",
					"shelf_life_from": 2,
					"shelf_life_to": 3,
					"shelf_life_type": 1,
					"origin": "Sør- og Mellom-Amerika",
					"is_sponsored": 0,
					"sponsor_name": null,
					"default_amount_type_id": null,
					"published_from": "2015-11-23 00:00:00",
					"published_to": null,
					"created_by": 5,
					"updated_by": 5,
					"created_at": "2015-11-24 16:22:29",
					"updated_at": "2017-05-05 17:01:02",
					"url": "http://www.dagbladet.medialaben.no/mat/ingrediens/kalkun",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/ingrediens/kalkun",
					"pivot": {
						"ingredientable_id": 276,
						"ingredient_id": 435
					},
					"images": [
						{
							"id": 734,
							"is_profile": 0,
							"type": 3,
							"file_name": "ae9cf8f3",
							"size": 986794,
							"width": 3000,
							"height": 2250,
							"title": "Kalkun",
							"description": null,
							"byline": "matprat.no / Mari Svenningsen",
							"byline_url": "http://www.matprat.no/",
							"created_by": 5,
							"updated_by": 5,
							"created_at": "2015-11-24 16:26:13",
							"updated_at": "2015-11-24 16:30:32",
							"type_original": 0,
							"url_s_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/1/ae9cf8f3-kalkun.jpg",
							"url_m_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/1/ae9cf8f3-kalkun.jpg",
							"url_l_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/1/ae9cf8f3-kalkun.jpg",
							"url_xl_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/1/ae9cf8f3-kalkun.jpg",
							"url_s_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/2/ae9cf8f3-kalkun.jpg",
							"url_m_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/2/ae9cf8f3-kalkun.jpg",
							"url_l_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/2/ae9cf8f3-kalkun.jpg",
							"url_xl_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/2/ae9cf8f3-kalkun.jpg",
							"url_s_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/3/ae9cf8f3-kalkun.jpg",
							"url_m_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/3/ae9cf8f3-kalkun.jpg",
							"url_l_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/3/ae9cf8f3-kalkun.jpg",
							"url_xl_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/3/ae9cf8f3-kalkun.jpg",
							"seo_file_name": "ae9cf8f3-kalkun.jpg"
						}
					]
				}
			],
			"related_recipes": [
				{
					"id": 38,
					"views": 1085,
					"title": "Kalkunburger med mangosalsa",
					"slug": "kalkunburger-med-mangosalsa",
					"description_short": "Kalkunburgeren er et litt lettere alternativ til okseburgeren.",
					"description": "<p>Kalkunburgeren er et&nbsp;litt lettere alternativ til okseburgeren, med en sommerlig mangosalsa og smakfull krydret bl&aring;muggost.</p>",
					"time_total": 60,
					"time_cooking": null,
					"difficulty": 1,
					"servings": 4,
					"heat_scale": 0,
					"is_sponsored": 0,
					"sponsor_name": null,
					"published_from": "2015-07-23 15:47:25",
					"published_to": null,
					"created_by": 5,
					"updated_by": 5,
					"created_at": "2015-07-01 15:50:23",
					"updated_at": "2017-05-14 20:19:02",
					"draft": 0,
					"numVotes": 0,
					"rating": 0,
					"maxRating": null,
					"minRating": null,
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrift/kalkunburger-med-mangosalsa",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/oppskrift/kalkunburger-med-mangosalsa",
					"time_prep": 0,
					"images": [
						{
							"id": 164,
							"is_profile": 0,
							"type": 3,
							"file_name": "89dfceab",
							"size": 1238642,
							"width": 3000,
							"height": 2309,
							"title": "Kalkunburger med blåmuggost",
							"description": "<p><strong>SPENNENDE:</strong> Burger med mangosalsa og bl&aring;muggost.</p>",
							"byline": "matprat.no",
							"byline_url": "http://www.matprat.no/",
							"created_by": 5,
							"updated_by": 5,
							"created_at": "2015-07-01 15:40:58",
							"updated_at": "2015-10-27 18:56:34",
							"type_original": 0,
							"url_s_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/1/89dfceab-kalkunburger-med-blamuggost.jpg",
							"url_m_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/1/89dfceab-kalkunburger-med-blamuggost.jpg",
							"url_l_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/1/89dfceab-kalkunburger-med-blamuggost.jpg",
							"url_xl_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/1/89dfceab-kalkunburger-med-blamuggost.jpg",
							"url_s_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/2/89dfceab-kalkunburger-med-blamuggost.jpg",
							"url_m_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/2/89dfceab-kalkunburger-med-blamuggost.jpg",
							"url_l_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/2/89dfceab-kalkunburger-med-blamuggost.jpg",
							"url_xl_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/2/89dfceab-kalkunburger-med-blamuggost.jpg",
							"url_s_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/3/89dfceab-kalkunburger-med-blamuggost.jpg",
							"url_m_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/3/89dfceab-kalkunburger-med-blamuggost.jpg",
							"url_l_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/3/89dfceab-kalkunburger-med-blamuggost.jpg",
							"url_xl_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/3/89dfceab-kalkunburger-med-blamuggost.jpg",
							"seo_file_name": "89dfceab-kalkunburger-med-blamuggost.jpg"
						}
					]
				},
				{
					"id": 443,
					"views": 50680,
					"title": "Kyllinggryte med urter",
					"slug": "kyllinggryte-med-urter",
					"description_short": "Andreas Viestads franskinspirerte kyllinggryte kan varieres i det uendelige. Det har han gjort.\n",
					"description": "<p>Jeg lager en franskinspirert kyllingrett med estragon, men her er det ingenting i veien for &aring; bruke timian eller oregano, hvis du liker det bedre. Og hvis noen sier at man ikke kan bruke salvie eller rosmarin til kylling, ikke h&oslash;r p&aring; dem. (Basilikum funker d&aring;rligere i denne retten, den har en tendens til &aring; kollapse.) Helst friske urter, men t&oslash;rka funker ogs&aring;.</p>\n<p>Server med gr&oslash;nn salat, gr&oslash;nne b&oslash;nner og poteter. (Det beste er g&aring;rsdagens kokte poteter, delt i fire og stekt i panna.)</p>\n<p>Denne oppskriften er hentet fra Andreas Viestads <em><a href=\"/2016/01/30/tema/mat/viestad/matsiden/andreas_viestad/42936535/\">Det beste jeg vet: Denne retten har jeg laget 500 ganger.</a></em></p>",
					"time_total": 35,
					"time_cooking": 15,
					"difficulty": 1,
					"servings": 4,
					"heat_scale": 0,
					"is_sponsored": 0,
					"sponsor_name": null,
					"published_from": "2016-01-30 10:00:00",
					"published_to": null,
					"created_by": 5,
					"updated_by": 3,
					"created_at": "2016-01-26 11:44:16",
					"updated_at": "2017-05-15 09:04:02",
					"draft": 0,
					"numVotes": 0,
					"rating": 0,
					"maxRating": null,
					"minRating": null,
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrift/kyllinggryte-med-urter",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/oppskrift/kyllinggryte-med-urter",
					"time_prep": 20,
					"images": [
						{
							"id": 1018,
							"is_profile": 0,
							"type": 3,
							"file_name": "ce564840",
							"size": 1064758,
							"width": 3000,
							"height": 2000,
							"title": "Kyllinggryte Viestad",
							"description": null,
							"byline": "Mette Randem",
							"byline_url": null,
							"created_by": 5,
							"updated_by": 5,
							"created_at": "2016-01-26 16:24:17",
							"updated_at": "2016-01-26 16:24:17",
							"type_original": 0,
							"url_s_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/1/ce564840-kyllinggryte-viestad.jpg",
							"url_m_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/1/ce564840-kyllinggryte-viestad.jpg",
							"url_l_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/1/ce564840-kyllinggryte-viestad.jpg",
							"url_xl_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/1/ce564840-kyllinggryte-viestad.jpg",
							"url_s_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/2/ce564840-kyllinggryte-viestad.jpg",
							"url_m_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/2/ce564840-kyllinggryte-viestad.jpg",
							"url_l_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/2/ce564840-kyllinggryte-viestad.jpg",
							"url_xl_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/2/ce564840-kyllinggryte-viestad.jpg",
							"url_s_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/3/ce564840-kyllinggryte-viestad.jpg",
							"url_m_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/3/ce564840-kyllinggryte-viestad.jpg",
							"url_l_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/3/ce564840-kyllinggryte-viestad.jpg",
							"url_xl_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/3/ce564840-kyllinggryte-viestad.jpg",
							"seo_file_name": "ce564840-kyllinggryte-viestad.jpg"
						}
					]
				},
				{
					"id": 28,
					"views": 30771,
					"title": "Brimis kjøttkaker",
					"slug": "brimis-kjottkaker",
					"description_short": null,
					"description": "<p>Kj&oslash;ttkaker, hjemmelaget brun saus, k&aring;lstuing og nyr&oslash;rte tytteb&aelig;r er en perfekt helgemiddag for hele familien. Brimi husker&nbsp;godt fra barndommen, lukta i huset n&aring;r sausen var p&aring; gang.</p>",
					"time_total": 40,
					"time_cooking": 25,
					"difficulty": 2,
					"servings": 4,
					"heat_scale": 0,
					"is_sponsored": 0,
					"sponsor_name": null,
					"published_from": "2015-10-28 15:52:01",
					"published_to": null,
					"created_by": 5,
					"updated_by": 7,
					"created_at": "2015-06-30 15:52:01",
					"updated_at": "2017-05-15 09:30:02",
					"draft": 0,
					"numVotes": 0,
					"rating": 0,
					"maxRating": null,
					"minRating": null,
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrift/brimis-kjottkaker",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/oppskrift/brimis-kjottkaker",
					"time_prep": 15,
					"images": [
						{
							"id": 153,
							"is_profile": 0,
							"type": 3,
							"file_name": "17163e27",
							"size": 925884,
							"width": 2143,
							"height": 3000,
							"title": "Hjemmelagde kjøttkaker",
							"description": "<p><strong>GODE SMAKER:</strong>&nbsp;Arne Brimi er glad i b&aring;de kj&oslash;ttkaker og medisterkaker. Kj&oslash;ttkakene lager han sj&oslash;l, mens medisterkaker kj&oslash;per han hos en lokal leverand&oslash;r eller bruker ferdig medisterdeig.&nbsp;</p>",
							"byline": "Mette Møller",
							"byline_url": null,
							"created_by": 5,
							"updated_by": 5,
							"created_at": "2015-06-30 15:44:25",
							"updated_at": "2015-10-29 17:06:43",
							"type_original": 0,
							"url_s_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/1/17163e27-hjemmelagde-kjottkaker.jpg",
							"url_m_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/1/17163e27-hjemmelagde-kjottkaker.jpg",
							"url_l_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/1/17163e27-hjemmelagde-kjottkaker.jpg",
							"url_xl_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/1/17163e27-hjemmelagde-kjottkaker.jpg",
							"url_s_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/2/17163e27-hjemmelagde-kjottkaker.jpg",
							"url_m_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/2/17163e27-hjemmelagde-kjottkaker.jpg",
							"url_l_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/2/17163e27-hjemmelagde-kjottkaker.jpg",
							"url_xl_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/2/17163e27-hjemmelagde-kjottkaker.jpg",
							"url_s_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/3/17163e27-hjemmelagde-kjottkaker.jpg",
							"url_m_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/3/17163e27-hjemmelagde-kjottkaker.jpg",
							"url_l_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/3/17163e27-hjemmelagde-kjottkaker.jpg",
							"url_xl_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/3/17163e27-hjemmelagde-kjottkaker.jpg",
							"seo_file_name": "17163e27-hjemmelagde-kjottkaker.jpg"
						}
					]
				},
				{
					"id": 416,
					"views": 29478,
					"title": "Viltgryte med reinskav",
					"slug": "viltgryte-med-reinskav",
					"description_short": "Deilig viltgryte med reinskav, sopp og bacon.",
					"description": "<p>I denne viltgryten finner du b&aring;de reinskav, sopp og bacon i smaksrik saus med b&aring;de r&oslash;mme, fl&oslash;te og brunost. Oppskriften kan du gj&oslash;re til din etterhvert som du f&aring;r erfaring. Det er bare &aring; legge til og trekke fra og f&aring; retten slik du liker den best. NRK-profil Anne Rimmen og motocrosskj&oslash;reren Ailo Gaup serverer den med lettdampet brokkoli og poteter eller ris.</p>",
					"time_total": 80,
					"time_cooking": 20,
					"difficulty": 1,
					"servings": 4,
					"heat_scale": 0,
					"is_sponsored": 0,
					"sponsor_name": null,
					"published_from": "2016-01-09 12:00:00",
					"published_to": null,
					"created_by": 4,
					"updated_by": 4,
					"created_at": "2016-01-08 22:16:14",
					"updated_at": "2017-05-15 08:50:02",
					"draft": 0,
					"numVotes": 0,
					"rating": 0,
					"maxRating": null,
					"minRating": null,
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrift/viltgryte-med-reinskav",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/oppskrift/viltgryte-med-reinskav",
					"time_prep": 60,
					"images": [
						{
							"id": 962,
							"is_profile": 0,
							"type": 3,
							"file_name": "23b7e8eb",
							"size": 840956,
							"width": 2184,
							"height": 1456,
							"title": "Viltgryte med reinskav",
							"description": "<p><strong>GJESTEMAT:</strong>Viltgryte st&aring;r ofte p&aring; menyen n&aring;r NRK-profil Anne Rimmen og samboeren, motocrosskj&oslash;reren Ailo Gaup, inviterer gjester.</p>",
							"byline": "Dagbladet",
							"byline_url": "http://www.dagbladet.no",
							"created_by": 4,
							"updated_by": 4,
							"created_at": "2016-01-08 22:06:41",
							"updated_at": "2016-01-09 00:24:44",
							"type_original": 0,
							"url_s_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/1/23b7e8eb-viltgryte-med-reinskav.jpg",
							"url_m_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/1/23b7e8eb-viltgryte-med-reinskav.jpg",
							"url_l_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/1/23b7e8eb-viltgryte-med-reinskav.jpg",
							"url_xl_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/1/23b7e8eb-viltgryte-med-reinskav.jpg",
							"url_s_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/2/23b7e8eb-viltgryte-med-reinskav.jpg",
							"url_m_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/2/23b7e8eb-viltgryte-med-reinskav.jpg",
							"url_l_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/2/23b7e8eb-viltgryte-med-reinskav.jpg",
							"url_xl_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/2/23b7e8eb-viltgryte-med-reinskav.jpg",
							"url_s_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/3/23b7e8eb-viltgryte-med-reinskav.jpg",
							"url_m_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/3/23b7e8eb-viltgryte-med-reinskav.jpg",
							"url_l_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/3/23b7e8eb-viltgryte-med-reinskav.jpg",
							"url_xl_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/3/23b7e8eb-viltgryte-med-reinskav.jpg",
							"seo_file_name": "23b7e8eb-viltgryte-med-reinskav.jpg"
						}
					]
				},
				{
					"id": 401,
					"views": 25062,
					"title": "Grytepasta med tomat",
					"slug": "grytepasta-med-tomat",
					"description_short": "Enklere blir det ikke: Lag hele pastaretten i én gryte. ",
					"description": "<p>Noen ganger vil vi ha det enkelt. Enkle oppskrifter med f&aring; ingredienser som tar kort tid &aring; lage, som krever minimalt med utstyr.</p>\n<p>Og det beste av alt? Det smaker fantastisk godt.</p>\n<p>Her er en enkel grunnoppskrift, og s&aring; kan du variere krydder og smakstilsetninger etter eget &oslash;nske.</p>\n<p>Pastamengden er raus, s&aring; om du har i mer mettende gr&oslash;nnsaker eller serverer salat til, kan du godt kutte den noe - men husk &aring; kutte vannmengden tilsvarende.</p>",
					"time_total": 15,
					"time_cooking": 5,
					"difficulty": 1,
					"servings": 4,
					"heat_scale": 0,
					"is_sponsored": 0,
					"sponsor_name": null,
					"published_from": "2016-01-04 13:00:00",
					"published_to": null,
					"created_by": 3,
					"updated_by": 3,
					"created_at": "2015-12-30 01:34:29",
					"updated_at": "2017-05-14 18:49:02",
					"draft": 0,
					"numVotes": 0,
					"rating": 0,
					"maxRating": null,
					"minRating": null,
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrift/grytepasta-med-tomat",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/oppskrift/grytepasta-med-tomat",
					"time_prep": 10,
					"images": [
						{
							"id": 949,
							"is_profile": 0,
							"type": 3,
							"file_name": "4a1aaa87",
							"size": 689070,
							"width": 3000,
							"height": 1993,
							"title": "Spaghetti pomodoro",
							"description": "<p><em><strong>SPAGHETTI POMODORO: </strong></em>Klassisk italiensk tomatpasta, og den blir like god om du lager den i &eacute;n gryte.</p>",
							"byline": "Shutterstock / NTB Scanpix",
							"byline_url": null,
							"created_by": 3,
							"updated_by": 3,
							"created_at": "2016-01-04 12:52:59",
							"updated_at": "2016-01-04 12:52:59",
							"type_original": 0,
							"url_s_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/1/4a1aaa87-spaghetti-pomodoro.jpg",
							"url_m_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/1/4a1aaa87-spaghetti-pomodoro.jpg",
							"url_l_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/1/4a1aaa87-spaghetti-pomodoro.jpg",
							"url_xl_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/1/4a1aaa87-spaghetti-pomodoro.jpg",
							"url_s_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/2/4a1aaa87-spaghetti-pomodoro.jpg",
							"url_m_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/2/4a1aaa87-spaghetti-pomodoro.jpg",
							"url_l_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/2/4a1aaa87-spaghetti-pomodoro.jpg",
							"url_xl_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/2/4a1aaa87-spaghetti-pomodoro.jpg",
							"url_s_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/3/4a1aaa87-spaghetti-pomodoro.jpg",
							"url_m_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/3/4a1aaa87-spaghetti-pomodoro.jpg",
							"url_l_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/3/4a1aaa87-spaghetti-pomodoro.jpg",
							"url_xl_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/3/4a1aaa87-spaghetti-pomodoro.jpg",
							"seo_file_name": "4a1aaa87-spaghetti-pomodoro.jpg"
						}
					]
				},
				{
					"id": 369,
					"views": 14325,
					"title": "Vegisterkaker",
					"slug": "vegisterkaker",
					"description_short": "Veganmisjonens berømte vegisterkaker, perfekt å servere til jul.",
					"description": "<p>Vegisterkaker er sm&aring; herligheter som smaker akkurat slik de skal gj&oslash;re, spr&oslash; utenp&aring; og myke inni.</p>\n<p>Disse er perfekt til julekvelden, men kan fint spises resten av &aring;ret ogs&aring;.</p>\n<p>Denne oppskriften gir deg 30-35 vegisterkaker.</p>",
					"time_total": 60,
					"time_cooking": 40,
					"difficulty": 1,
					"servings": 6,
					"heat_scale": 0,
					"is_sponsored": 0,
					"sponsor_name": null,
					"published_from": "2015-12-22 13:00:00",
					"published_to": null,
					"created_by": 7,
					"updated_by": 3,
					"created_at": "2015-12-22 10:56:36",
					"updated_at": "2017-05-14 22:21:02",
					"draft": 0,
					"numVotes": 0,
					"rating": 0,
					"maxRating": null,
					"minRating": null,
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrift/vegisterkaker",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/oppskrift/vegisterkaker",
					"time_prep": 20,
					"images": [
						{
							"id": 884,
							"is_profile": 0,
							"type": 3,
							"file_name": "3f122254",
							"size": 1095196,
							"width": 2250,
							"height": 3000,
							"title": "Vegisterkaker",
							"description": "<p><strong>POPUL&AElig;R:</strong> Den mest popul&aelig;re oppskriften p&aring; Veganmisjonens hjemmeside er den vegetariske versjonen av medisterkaker.</p>",
							"byline": "Dreyer Hensley Studios",
							"byline_url": null,
							"created_by": 7,
							"updated_by": 7,
							"created_at": "2015-12-22 09:58:18",
							"updated_at": "2015-12-22 09:58:30",
							"type_original": 0,
							"url_s_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/1/3f122254-vegisterkaker.jpg",
							"url_m_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/1/3f122254-vegisterkaker.jpg",
							"url_l_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/1/3f122254-vegisterkaker.jpg",
							"url_xl_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/1/3f122254-vegisterkaker.jpg",
							"url_s_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/2/3f122254-vegisterkaker.jpg",
							"url_m_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/2/3f122254-vegisterkaker.jpg",
							"url_l_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/2/3f122254-vegisterkaker.jpg",
							"url_xl_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/2/3f122254-vegisterkaker.jpg",
							"url_s_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/3/3f122254-vegisterkaker.jpg",
							"url_m_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/3/3f122254-vegisterkaker.jpg",
							"url_l_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/3/3f122254-vegisterkaker.jpg",
							"url_xl_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/3/3f122254-vegisterkaker.jpg",
							"seo_file_name": "3f122254-vegisterkaker.jpg"
						}
					]
				},
				{
					"id": 292,
					"views": 13766,
					"title": "Espelid og Hellstrøms ribbe",
					"slug": "espelid-og-hellstroms-ribbe",
					"description_short": "Ribba kan lages til julaften, mens du i romjula kan fortsette å spise den - den er nemlig ofte best kald.",
					"description": "<p>Det fine med ribbe er at den holder noen dager utover i jula og ofte er best kald.</p>\n<p>Svoren er nesten viktigst av alt. Flere faktorer avgj&oslash;r om du f&aring;r den knasende spr&oslash;: kvaliteten p&aring; kj&oslash;ttet, nok v&aelig;ske og riktig temperatur.</p>\n<p><strong>F&oslash;lger du denne oppskriften, blir svoren perfekt:</strong></p>\n<p>&bull; Ikke kj&oslash;p den magreste ribba, da er det vanskelig &aring; f&aring; spr&oslash; svor.<br /><br />&bull; Stor ribbe er en fordel, ikke v&aelig;r redd for at den er for feit. <br /><br />&bull; Riss sm&aring; ruter i svoren, den skal v&aelig;re lett &aring; skj&aelig;re - og lett &aring; tygge.<br /><br />&bull; Stek ribba f&oslash;rst &eacute;n time med svoren ned. Ha passe med v&aelig;ske i langpanna, ca. 2 kopper kaldt vann. <br /><br />&bull; Snu ribba etter &eacute;n time, &oslash;s kaldt vann over, og la den ligge med svoren opp like lenge. S&oslash;rg for &aring; ha nok v&aelig;ske i panna. <br /><br />&bull; La ribba deretter steke i ytterligere en halv time (eller lenger &mdash; avhenger av tykkelsen p&aring; ribba) mens du &oslash;ser v&aelig;ske over svoren hvert 5. minutt. <br /><br />&bull; Ovner er forskjellige, men s&oslash;rg for &aring; holde temperaturen et sted mellom 150 og 180 grader. Langsteking er alltid bedre enn hurtigstekning, s&aring; det l&oslash;nner seg ikke &aring; ha for varm ovn. <br />&nbsp;<br />&bull; Fremdeles redd for at svoren ikke blir spr&oslash;? Sett ribba litt h&oslash;yere i ovnen og skru opp temperaturen mot slutten av steiketida. Pass p&aring; hele tida s&aring; ribba ikke blir brent.</p>",
					"time_total": 180,
					"time_cooking": 30,
					"difficulty": 2,
					"servings": 4,
					"heat_scale": 0,
					"is_sponsored": 0,
					"sponsor_name": null,
					"published_from": "2010-12-23 05:00:00",
					"published_to": null,
					"created_by": 7,
					"updated_by": 12,
					"created_at": "2015-12-01 15:19:32",
					"updated_at": "2017-05-14 22:27:02",
					"draft": 0,
					"numVotes": 0,
					"rating": 0,
					"maxRating": null,
					"minRating": null,
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrift/espelid-og-hellstroms-ribbe",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/oppskrift/espelid-og-hellstroms-ribbe",
					"time_prep": 150,
					"images": [
						{
							"id": 768,
							"is_profile": 0,
							"type": 3,
							"file_name": "40e6abb2",
							"size": 951725,
							"width": 2000,
							"height": 2485,
							"title": "Espelid og Hellstrøms juleribbe",
							"description": "<p><strong>SKIKKELIG JULEMIDDAG:</strong> Ribbe er digg uansett om den er varm eller kald. Pass bare p&aring; s&aring; du f&aring;r svoren spr&oslash;!</p>",
							"byline": "Øistein Norum Monsen/Dagbladet",
							"byline_url": null,
							"created_by": 7,
							"updated_by": 7,
							"created_at": "2015-12-01 15:16:22",
							"updated_at": "2015-12-17 13:21:35",
							"type_original": 0,
							"url_s_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/1/40e6abb2-espelid-og-hellstroms-juleribbe.jpg",
							"url_m_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/1/40e6abb2-espelid-og-hellstroms-juleribbe.jpg",
							"url_l_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/1/40e6abb2-espelid-og-hellstroms-juleribbe.jpg",
							"url_xl_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/1/40e6abb2-espelid-og-hellstroms-juleribbe.jpg",
							"url_s_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/2/40e6abb2-espelid-og-hellstroms-juleribbe.jpg",
							"url_m_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/2/40e6abb2-espelid-og-hellstroms-juleribbe.jpg",
							"url_l_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/2/40e6abb2-espelid-og-hellstroms-juleribbe.jpg",
							"url_xl_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/2/40e6abb2-espelid-og-hellstroms-juleribbe.jpg",
							"url_s_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/3/40e6abb2-espelid-og-hellstroms-juleribbe.jpg",
							"url_m_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/3/40e6abb2-espelid-og-hellstroms-juleribbe.jpg",
							"url_l_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/3/40e6abb2-espelid-og-hellstroms-juleribbe.jpg",
							"url_xl_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/3/40e6abb2-espelid-og-hellstroms-juleribbe.jpg",
							"seo_file_name": "40e6abb2-espelid-og-hellstroms-juleribbe.jpg"
						}
					]
				},
				{
					"id": 872,
					"views": 13745,
					"title": "Ribbe som er langtidsstekt",
					"slug": "ribbe-som-er-langtidsstekt",
					"description_short": "Ribbe som er langtidsstekt",
					"description": "<p>Ribbe som er langtidsstekt</p>",
					"time_total": 900,
					"time_cooking": null,
					"difficulty": 1,
					"servings": 6,
					"heat_scale": 0,
					"is_sponsored": 0,
					"sponsor_name": null,
					"published_from": "2016-12-14 00:00:00",
					"published_to": null,
					"created_by": 12,
					"updated_by": 12,
					"created_at": "2016-12-14 13:18:58",
					"updated_at": "2017-05-15 07:30:01",
					"draft": 0,
					"numVotes": 0,
					"rating": 0,
					"maxRating": null,
					"minRating": null,
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrift/ribbe-som-er-langtidsstekt",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/oppskrift/ribbe-som-er-langtidsstekt",
					"time_prep": 0,
					"images": [
						{
							"id": 1704,
							"is_profile": 0,
							"type": 3,
							"file_name": "e93ae4b0",
							"size": 1332930,
							"width": 3000,
							"height": 2000,
							"title": "Ribbe blir best med denne teknikken. ",
							"description": "<p>Ribbe blir best om du langtidssteker.&nbsp;</p>",
							"byline": "LIsbeth Michelsen",
							"byline_url": null,
							"created_by": 12,
							"updated_by": 12,
							"created_at": "2016-12-14 15:59:20",
							"updated_at": "2016-12-14 15:59:20",
							"type_original": 0,
							"url_s_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/1/e93ae4b0-ribbe-blir-best-med-denne-teknikken-.jpg",
							"url_m_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/1/e93ae4b0-ribbe-blir-best-med-denne-teknikken-.jpg",
							"url_l_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/1/e93ae4b0-ribbe-blir-best-med-denne-teknikken-.jpg",
							"url_xl_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/1/e93ae4b0-ribbe-blir-best-med-denne-teknikken-.jpg",
							"url_s_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/2/e93ae4b0-ribbe-blir-best-med-denne-teknikken-.jpg",
							"url_m_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/2/e93ae4b0-ribbe-blir-best-med-denne-teknikken-.jpg",
							"url_l_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/2/e93ae4b0-ribbe-blir-best-med-denne-teknikken-.jpg",
							"url_xl_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/2/e93ae4b0-ribbe-blir-best-med-denne-teknikken-.jpg",
							"url_s_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/3/e93ae4b0-ribbe-blir-best-med-denne-teknikken-.jpg",
							"url_m_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/3/e93ae4b0-ribbe-blir-best-med-denne-teknikken-.jpg",
							"url_l_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/3/e93ae4b0-ribbe-blir-best-med-denne-teknikken-.jpg",
							"url_xl_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/3/e93ae4b0-ribbe-blir-best-med-denne-teknikken-.jpg",
							"seo_file_name": "e93ae4b0-ribbe-blir-best-med-denne-teknikken-.jpg"
						}
					]
				},
				{
					"id": 444,
					"views": 12743,
					"title": "Kyllinggryte med grønn karri",
					"slug": "kyllinggryte-med-gronn-karri",
					"description_short": "Enkel å lage – særlig hvis du bruker grønn karripasta på boks. En rett du kan lage ulike variasjoner rundt – med ulike krydder og grønnsaker.",
					"description": "<p>Enkel &aring; lage &ndash; s&aelig;rlig hvis du bruker s&aring;nn gr&oslash;nn karripasta p&aring; boks. Samtidig en rett du kan lage en hel haug med ulike variasjoner rundt &ndash; med ulike krydder og gr&oslash;nnsaker.</p>\n<p>Innenfor samme smaksbilde er det ekstra godt med sitrongress, limeblad, pak choi, gr&oslash;nne erter og sjampinjong. Bytt til r&oslash;d karripasta, s&aring; kan du leke med paprika, s&oslash;tpotet, gresskar og k&aring;lrot.</p>\n<p>Server med kokt jasminris.</p>\n<p>Oppskriften er hentet fra Andreas Viestads <a href=\"/2016/01/30/tema/mat/viestad/matsiden/andreas_viestad/42936535/\">Det beste jeg vet: Denne retten har jeg laget 500 ganger</a></p>",
					"time_total": 30,
					"time_cooking": 15,
					"difficulty": 1,
					"servings": 4,
					"heat_scale": 0,
					"is_sponsored": 0,
					"sponsor_name": null,
					"published_from": "2016-01-30 10:00:00",
					"published_to": null,
					"created_by": 5,
					"updated_by": 3,
					"created_at": "2016-01-26 16:25:40",
					"updated_at": "2017-05-15 07:26:01",
					"draft": 0,
					"numVotes": 0,
					"rating": 0,
					"maxRating": null,
					"minRating": null,
					"url": "http://www.dagbladet.medialaben.no/mat/oppskrift/kyllinggryte-med-gronn-karri",
					"url_embed": "http://www.dagbladet.medialaben.no/mat/embed/oppskrift/kyllinggryte-med-gronn-karri",
					"time_prep": 15,
					"images": [
						{
							"id": 1017,
							"is_profile": 0,
							"type": 3,
							"file_name": "2760990f",
							"size": 642321,
							"width": 3000,
							"height": 2000,
							"title": "Kyllinggryte med grønn karri",
							"description": null,
							"byline": "Mette Randem",
							"byline_url": null,
							"created_by": 5,
							"updated_by": 5,
							"created_at": "2016-01-26 16:23:45",
							"updated_at": "2016-01-26 16:23:45",
							"type_original": 0,
							"url_s_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/1/2760990f-kyllinggryte-med-gronn-karri.jpg",
							"url_m_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/1/2760990f-kyllinggryte-med-gronn-karri.jpg",
							"url_l_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/1/2760990f-kyllinggryte-med-gronn-karri.jpg",
							"url_xl_landscape": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/1/2760990f-kyllinggryte-med-gronn-karri.jpg",
							"url_s_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/2/2760990f-kyllinggryte-med-gronn-karri.jpg",
							"url_m_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/2/2760990f-kyllinggryte-med-gronn-karri.jpg",
							"url_l_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/2/2760990f-kyllinggryte-med-gronn-karri.jpg",
							"url_xl_portrait": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/2/2760990f-kyllinggryte-med-gronn-karri.jpg",
							"url_s_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/s/3/2760990f-kyllinggryte-med-gronn-karri.jpg",
							"url_m_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/m/3/2760990f-kyllinggryte-med-gronn-karri.jpg",
							"url_l_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/l/3/2760990f-kyllinggryte-med-gronn-karri.jpg",
							"url_xl_profile": "http://www.dagbladet.medialaben.no/mat/bilder/c/xl/3/2760990f-kyllinggryte-med-gronn-karri.jpg",
							"seo_file_name": "2760990f-kyllinggryte-med-gronn-karri.jpg"
						}
					]
				}
			]
		};

console.log('******************************************',
	fakeProp.images.url_xl_landscape
	);

const MainRecipe = (props) => (
	<Wrapper>
		<Row>
			<Col md={7}>
				<MainRecipeImage src={ fakeProp.images[0].url_l_landscape } />
			</Col>
			<Col md={5}>
				<ComplexitySection>
					<IconsBar entities={[{ name: 'difficulty' }, { name: 'activityTime' }, { name: 'totalTime' }]} />
					<ComplexitySectionHeader>{fakeProp.title}</ComplexitySectionHeader>
				</ComplexitySection>
			</Col>
		</Row>
		<Row>
			<Col md={6}>
				<DetailsSection  />
			</Col>
			<Col md={6}>
				<Description>
					<span>{ fakeProp.description.replace(/<\/?[^>]+>/g,'') }
					</span>
				</Description>
			</Col>
		</Row>
		<Steps />
	</Wrapper>
);

export { MainRecipe };
